# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valve_port_setter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(173, 106)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 10, 111, 41))
        self.widget.setMaximumSize(QtCore.QSize(111, 41))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(60, 0, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 47, 13))
        self.label.setObjectName("label")
        self.Valve_2 = QtWidgets.QSpinBox(self.widget)
        self.Valve_2.setGeometry(QtCore.QRect(60, 10, 42, 22))
        self.Valve_2.setMinimum(1)
        self.Valve_2.setMaximum(8)
        self.Valve_2.setObjectName("Valve_2")
        self.Valve = QtWidgets.QSpinBox(self.widget)
        self.Valve.setGeometry(QtCore.QRect(10, 10, 42, 22))
        self.Valve.setMinimum(1)
        self.Valve.setMaximum(24)
        self.Valve.setObjectName("Valve")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Port"))
        self.label.setText(_translate("Form", "Valve"))
