; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "qmcontrol"
#ifndef Version
#define public Version "development"
#endif
#define MyAppPublisher "Q Magnetics"
#define MyAppURL "https://www.qmagnetics.com/"
#define MyAppExeName "qmcontrol.exe"
#define ProgData "C:\ProgramData\QMagnetics"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A5AB38DD-8A2A-4A46-8DAC-F87771E33754}
AppName={#MyAppName}
AppVersion={#Version}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename="QMControl-{#Version}"
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Dirs]
Name: "{#ProgData}"; Permissions: users-modify
Name: "{#ProgData}\settings"; Permissions: users-modify
Name: "{#ProgData}\shims"; Permissions: users-modify
Name: "{#ProgData}\nmr_data"; Permissions: users-modify
Name: "{#ProgData}\logs"; Permissions: users-modify

[Files]
Source: "{#SourcePath}\dist\qmcontrol\{#MyAppExeName}"; DestDir: "{app}"; Permissions: users-modify; Flags: ignoreversion
Source: "{#SourcePath}\dist\qmcontrol\*"; DestDir: "{app}"; Permissions: users-modify; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourcePath}\qmcontrol\settings\*"; DestDir: "{#ProgData}\settings";  Permissions: users-modify; Flags: ignoreversion onlyifdoesntexist
Source: "{#SourcePath}\qmcontrol\shims\*"; DestDir: "{#ProgData}\shims"; Permissions: users-modify; Flags: ignoreversion onlyifdoesntexist
Source: "{#SourcePath}\FrontPanelUSB-DriverOnly-5.2.2.exe"; DestDir: "{app}"; Permissions: users-modify; Flags: ignoreversion deleteafterinstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\FrontPanelUSB-DriverOnly-5.2.2.exe"; Description: "Running Opal Kelly driver install";
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

