# -*- coding: utf-8 -*-
"""
Q Magnetics NMR spectrometer control UI
"""
import json
import time
import statistics
from pathlib import Path
import logging
import os

import numpy as np
import matplotlib as mpl
from matplotlib.figure import Figure
from matplotlib.ticker import FormatStrFormatter
from matplotlib.backends.backend_qtagg import FigureCanvas, NavigationToolbar2QT
from pyqtgraph.parametertree import Parameter, ParameterTree, registerParameterType

from PySide6.QtCore import Qt, QSize, QTimer, QObject, Signal, Slot
from PySide6.QtGui import QTextCursor
from PySide6.QtWidgets import (
    QApplication,
    QWidget,
    QLabel,
    QDoubleSpinBox,
    QSlider,
    QVBoxLayout,
    QHBoxLayout,
    QMessageBox)

from qmcontrol.ui.qmcontrol import Ui_mainWindow            # generated by Qt Designer
from qmcontrol.utilities import simulated_pulse_acquire_run, simulated_shim_run  # simulated runs
from qmcontrol.interface_constants import settings_file    # filename and path for sticky settings
from qmcontrol.host_interface import SpectrometerInterface # spectrometer hardware interface
#from qmcontrol.nscan_pulse_acquire_run import nscan_pulse_acquire                # run
#from qmcontrol.shim_run import autoshim                                          # run
import qmcontrol.temp_ctrl as tc                           # magnet temperature controller
import qmcontrol.shim_system as ss                         # shim hardware
import qmcontrol.ext485 as ex4

from qmcontrol.runs.runs_registry import runs_list
from qmcontrol.components.directory_parameter import DirectoryParameter
from qmcontrol.qm_logger import GUIHandler
#from qmcontrol.version import Version as Qm_version
logger = logging.getLogger(__name__)

__author__ = "John Price"
__copyright__ = "Copyright 2021, Q Magnetics, LLC"
__credits__ = ["John Price", "Rainer Malzbender"]
__license__ = "undecided"
__version__ = "0.1"
__maintainer__ = "John Price"
__email__ = "john@qmagnetics.com"
__status__ = "development"

# stream object to redirect stdout and stderr to textEdit widget
class CustomStream(QObject):
    newText = Signal(str)
    def write(self,text):
        self.newText.emit(str(text))

class MainWindow(QWidget, Ui_mainWindow):
    hw_info_sig = Signal(object)
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.last_run = "scan"
        # UI constants
        self.phi_slider_range = 1000        # slider integer range +range to -range
        self.pivot_slider_range = 1000
        self.offset_slider_range = 1000 
        
        # tweak MainWindow
        self.resize(900, 600)
        self.setStyleSheet("QSplitter::handle{background: rgb(200, 200, 200);}")
        self.tabWidget.setTabEnabled(2,False)  # disable System tab
        
        # redirect stdout and stderr
        # (comment out to send to shell)
        for k,v in  logging.Logger.manager.loggerDict.items()  :
            if not isinstance(v, logging.PlaceHolder):
                for h in v.handlers:
                    if isinstance(h, GUIHandler):
                        h.emitter.log_sig.connect(self.onUpdateText)

        self.textEdit.setReadOnly(True)
        
        # make dict of all run class instances, keys are run names
        # also make list of run names, ie ["Pulse Acquire Run", "Shim Run",...]
        self.run_dict = {run_class.default_settings['name']: run_class(self) for run_class in runs_list}
        self.run_names = [run_class.default_settings['name'] for run_class in runs_list]

        # load saved settings file and create ParameterTree
        # if settings file is not found or can't be read, create ParameterTree from default settings
        # (see May 2020 commits on main branch for code to validate saved settings relative to defaults)
        logger.info(f"Load settings...")
        settings_error = False
        registerParameterType("directory", DirectoryParameter, override=False)
        if 2==1: #if settings_file.exists():
            try:
                with open(settings_file,'r') as sfile:
                    state = json.load(sfile)
                    self.p = Parameter.create(name='settings',type='group')
                    self.p.restoreState(state)
            except:
                logger.exception(f"Problem reading settings file ({settings_file}), will use default settings.")
                settings_error = True
        else:
            logger.info(f"Could not find settings file ({settings_file}), will use default settings.")
            settings_error = True

        if settings_error:
            default_settings = [self.global_default_settings]
            for key in self.run_dict:
                default_settings.append(self.run_dict[key].default_settings)
            self.p = Parameter.create(name='settings', type='group', children=default_settings)

        # add parameterTree to UI
        self.tree = ParameterTree()
        self.tree.setHeaderLabels(["Setting", "Value"])
        self.tree.setParameters(self.p, showTop=False)
        self.settingsFrameLayout = QHBoxLayout(self.settingsFrame)
        self.settingsFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.settingsFrameLayout.addWidget(self.tree)
  
        # initialize MainWindow splitter positions
        self.middleSplitter.setSizes([0,1])  # initial splitter positions
        self.mainHsplitter.setSizes([1,0])
         
        # runTab plot data state
        self.spect = []         # no spectrum yet, empty list
        self.freqs = []         # no frequencies yet
        self.fid = []           # no FID yet
        self.times = []         # no times yet
        
        # magTab plot data state
        self.mag_T = []          # magnet temperature
        self.mag_enclosure = []  # enclosure or ambient temperature
        self.mag_power = []      # magnet heater power
        self.mag_times = []      # times for magnet plots

        # initialize hardware interface
        # create SpectrometerInterface() instance and configure FPGA
        verbose = self.p.child('Global','Service','verbose').value()
        self.si=SpectrometerInterface(configure=True, verbose=verbose) 
        
        # matplotlib performance settings   
        mpl.rcParams['path.simplify'] = True                # mpl default True
        mpl.rcParams['path.simplify_threshold'] = 0.111111  # mpl default 1/9, 0->1, larger is faster
        mpl.rcParams['agg.path.chunksize'] = 0              # mpl default 0

        # set up runTab matplotlib canvas and interactive toolbar
        # axes are created in runTab_setup_one_subplot(), runTab_setup_two_subplots()   
        self.runTabCanvas = FigureCanvas(Figure()) 
        self.runTabToolbar = NavigationToolbar2QT(self.runTabCanvas, self)
        self.runTabToolbar.setStyleSheet("font-size: 10pt; padding-right: 30 px;") # fix tiny cursor font
        runTab_plot_layout = QVBoxLayout()
        runTab_plot_layout.addWidget(self.runTabToolbar)
        runTab_plot_layout.addWidget(self.runTabCanvas)
        self.runTabPlotFrame.setLayout(runTab_plot_layout)
        
        # set up magTab matplotlib canvas and interactive toolbar
        # axes are created in mag_setup_plots()     
        self.magTabCanvas = FigureCanvas(Figure()) 
        self.magTabToolbar = NavigationToolbar2QT(self.magTabCanvas, self)
        self.magTabToolbar.setStyleSheet("font-size: 10pt; padding-right: 30 px;") # fix tiny cursor font
        magTab_plot_layout = QVBoxLayout()
        magTab_plot_layout.addWidget(self.magTabToolbar)
        magTab_plot_layout.addWidget(self.magTabCanvas)
        self.magTabPlotFrame.setLayout(magTab_plot_layout)
        
        # populate runs select comboBox, initially at Pulse Acquire Run and Run tab 
        for run_name in self.run_names:
            run_name =  run_name.rstrip(' Run')
            self.runTabRunsComboBox.addItem(run_name)
        self.runTabRunsComboBox.setCurrentIndex(0)
        # self.runTabRunsComboBox.model().item(0).setEnabled(True)
     
        # signals, runTab UI slider changes
        self.runTabPhi0SliderC.sliderPressed.connect(self.phi0_slider_pressed)
        self.runTabPhi0SliderC.sliderMoved.connect(self.phi0_slider_moved)
        self.runTabPhi0SliderC.sliderReleased.connect(self.phi0_slider_released)
        self.runTabPhi0SliderF.sliderPressed.connect(self.phi0_slider_pressed)
        self.runTabPhi0SliderF.sliderMoved.connect(self.phi0_slider_moved)
        self.runTabPhi0SliderF.sliderReleased.connect(self.phi0_slider_released)
        
        self.runTabPhi1SliderC.sliderPressed.connect(self.phi1_slider_pressed)
        self.runTabPhi1SliderC.sliderMoved.connect(self.phi1_slider_moved)
        self.runTabPhi1SliderC.sliderReleased.connect(self.phi1_slider_released)
        self.runTabPhi1SliderF.sliderPressed.connect(self.phi1_slider_pressed)
        self.runTabPhi1SliderF.sliderMoved.connect(self.phi1_slider_moved)
        self.runTabPhi1SliderF.sliderReleased.connect(self.phi1_slider_released)
        
        self.runTabPivotSliderC.sliderPressed.connect(self.pivot_slider_pressed)
        self.runTabPivotSliderC.sliderMoved.connect(self.pivot_slider_moved)
        self.runTabPivotSliderC.sliderReleased.connect(self.pivot_slider_released)
        self.runTabPivotSliderF.sliderPressed.connect(self.pivot_slider_pressed)
        self.runTabPivotSliderF.sliderMoved.connect(self.pivot_slider_moved)
        self.runTabPivotSliderF.sliderReleased.connect(self.pivot_slider_released)
        
        self.runTab0ppmSliderC.sliderPressed.connect(self.ppmoffset_slider_pressed)
        self.runTab0ppmSliderC.sliderMoved.connect(self.ppmoffset_slider_moved)
        self.runTab0ppmSliderC.sliderReleased.connect(self.ppmoffset_slider_released)
        self.runTab0ppmSliderF.sliderPressed.connect(self.ppmoffset_slider_pressed)
        self.runTab0ppmSliderF.sliderMoved.connect(self.ppmoffset_slider_moved)
        self.runTab0ppmSliderF.sliderReleased.connect(self.ppmoffset_slider_released)
   
        # signals, other widget changes
        self.tabWidget.currentChanged.connect(self.tabWidget_current_changed)
        self.runTabRunsComboBox.currentIndexChanged.connect(self.runTabRunsComboBox_index_changed)
        self.runTabStartButton.pressed.connect(self.start_run_button_down)
        self.runTabFullXButton.pressed.connect(self.fullX_button_down)
        self.runTabFullYButton.pressed.connect(self.fullY_button_down)
        self.txFreqSpinBox.valueChanged.connect(self.txFreqSpinBox_changed)
        self.runTabHzCheckBox.stateChanged.connect(self.runTabHzCheckBox_changed)
        self.runTabFidCheckBox.stateChanged.connect(self.runTabFidCheckBox_changed)
        self.phasingCheckBox.stateChanged.connect(self.phasingCheckBox_changed)
        self.runTabTestCheckBox.stateChanged.connect(self.runTabTestCheckBox_changed)  
        
        # signals from Global settings in parameterTree widget
        self.p.child('Global','Tx freq').sigValueChanged.connect(self.global_txfreq_param_changed)
        self.p.child('Global','test scan').sigValueChanged.connect(self.testscan_param_changed)
        self.p.child('Global','show phasing').sigValueChanged.connect(self.showphasing_param_changed)
        self.p.child('Global','Hz plot').sigValueChanged.connect(self.hzplot_param_changed)
        self.p.child('Global','FID plot').sigValueChanged.connect(self.fidplot_param_changed)
        self.p.child('Global','trigger enable').sigValueChanged.connect(self.trig_enable_param_changed)
        
        # signals from phasing slider settings, every run must have these settings
        for run_name in self.run_names:
            self.p.child(run_name,'Processing','phase phi 0').sigValueChanged.connect(self.phasephi0_param_changed)
            self.p.child(run_name,'Processing','phase phi 1').sigValueChanged.connect(self.phasephi1_param_changed)
            self.p.child(run_name,'Processing','phase pivot').sigValueChanged.connect(self.phasepivot_param_changed)
            self.p.child(run_name,'Processing','ppm offset').sigValueChanged.connect(self.ppmoffset_param_changed)

        # initialize UI widgets that do not depend on which run is selected
        self.txFreqSpinBox.setValue(self.p.child('Global','Tx freq').value())
        self.runTabTestCheckBox.setChecked(self.p.child('Global','test scan').value())
        self.phasingCheckBox.setChecked(self.p.child('Global','show phasing').value()) 
        self.runTabPhaseFrame.setVisible(self.p.child('Global','show phasing').value())
        self.runTabStartButton.setText('Start')

        # need axes before any signals from these widgets
        self.runTabFidCheckBox.blockSignals(True)
        self.runTabFidCheckBox.setChecked(self.p.child('Global','FID plot').value())
        self.runTabFidCheckBox.blockSignals(False)
        self.runTabHzCheckBox.blockSignals(True)
        self.runTabHzCheckBox.setChecked(self.p.child('Global','Hz plot').value())
        self.runTabHzCheckBox.blockSignals(False)
            
        # magnet tab signals
        self.magTabSetPushButton.pressed.connect(self.mag_setParam_button_down)
        self.magTabPausePlotCheckBox.stateChanged.connect(self.magTabPausePlotCheckBox_state_changed)
        self.magTabSetTSpinBox.valueChanged.connect(self.magTabSetTSpinBox_changed)
        self.p.child('Global','Magnet','set point T').sigValueChanged.connect(self.mag_setT_param_changed)
        
        # report firmware versions
        # Do this only do this if spectrometer is present
        if verbose and self.si.is_present:
            tc_firmware_version,_,_ = tc.get_VER(self.si)
            logger.info(f"Temp. controller firmware version: {tc_firmware_version}")
            _,_,_,shim_firmware_version = ss.get_VER(self.si)
            logger.info(f"Shim driver firmware version: {shim_firmware_version}")
        
        # run is running flag
        # used to block unwanted actions while a run is running
        self.run_isrunning = False  
        
        # start magnet tab plots and UI
        # timer to synchronize data trasfer with sequencer
        self.mag_sample_delay = 12     # new point every 12 seconds
        self.mag_setup_plots()
        self.mag_timer = QTimer()
        self.mag_timer.timeout.connect(self.mag_plot) # callback for timeout event
        set_point_T = self.p.child('Global','Magnet','set point T').value()
        self.magTabSetTSpinBox.setValue(set_point_T)
        self.mag_plot()                  # first mag_plot() call
        self.mag_timer.start(self.mag_sample_delay*1000)
        

        self.trigger_timer_period = 1.0*1000                            # 1 second period
        self.trigger_timer =  QTimer()
        self.trigger_timer.timeout.connect(self.check_trigger) # callback for timeout event

        logger.info(f"Starting Trigger") 
        if self.p.child('Global','trigger enable').value():
            self.trigger_timer.start(self.trigger_timer_period)
    
        # trigger delay timer
        self.trigger_delay_timer = QTimer()
        self.trigger_delay_timer.setSingleShot(True)
        self.trigger_delay_timer.timeout.connect(self.trigger_delay_isover)
        
        # initialize Pulse Acquire Run 
        self.runTabRunsComboBox_index_changed(0)        

    @Slot()
    def on_hwQuery(self, ):
        hw_data = {}
        hw_data["present"] = self.si.is_present
        if hw_data["present"]:
            hw_data['deviceId'] = self.si.GetModelSerial()
            hw_data['serialNumber'] = self.si.HardwareKey()
            hw_data['usbInterface'] = str(self.si.USB_Interface())
            hw_data['usbSpeed'] = str(self.si.USB_Speed())
            hw_data['okProductVersion'] = self.si.OKProductName()
            hw_data['okAPIVersion'] = self.si.API_Version()

        self.hw_info_sig.emit(hw_data)

    @Slot()
    def save_settings(self,):
        state = self.p.saveState()
        logger.info(f'Saving settings to {settings_file}')
        with open(settings_file,'w') as sfile:
            json.dump(state,sfile, indent=4)
    
    #################
    # slots, all tabs
    @Slot(str)
    def onUpdateText(self, text):
        self.textEdit.moveCursor(QTextCursor.End)
        self.textEdit.insertPlainText(text)
        self.textEdit.insertPlainText("\n")
        self.textEdit.ensureCursorVisible()
    
    def tabWidget_current_changed(self,value):
        pass
    
    #TODO this needs to be changed to just start trigger_timer
    def trig_enable_param_changed(self,value):
        checked = self.p.child('Global','trigger enable').value()
        #logger.info(f'trig enable changed {checked}')  # for tests
        if self.checked:
            #ex4.clear_latches(self.si,'01')     # clear latched digital inputs set before change
            if checked: 
                self.trigger_timer.start(self.trigger_timer_period)
            else:
                self.trigger_timer.stop()
        else:
            logger.info(f"No trigger hardware present")
    
    def trigger_delay_isover(self):
        self.trigger_delay_timer.stop()
        self.start_run_button_down()
    
    def check_trigger(self):
        """Runs every 1sec to see if scan file is present in DIRECTORY"""
        self.TRIGGER_DIRECTORY = r".\..\..\scan_trigger.txt" #Normal Mode
        print("Checking")

        #logger.info(f'trigger timer tic')  # for tests
        if self.run_isrunning:     # do nothing if any run is active
            return
        if not self.p.child('Global','trigger enable').value():  # do nothing if not enabled
            return
        #if not self.trigger_hardware_present:
        #    return
        if not os.path.exists(self.TRIGGER_DIRECTORY):
            return
        else:
            #If file exists in directory, Trigger delay timmer to push start button
            logger.info(f'Hardware trigger detected')
            self.trigger_timer.stop()    # stop trigger timer, will be restarted by run
            #Read Trigger File, []
            with open(self.TRIGGER_DIRECTORY) as file:
                #trigger_info = [scan_type, scan_name, save directory, shim_file]
                self.trigger_info = file.read().splitlines() #Read each line in file as seperate list

       
            trigger_delay = self.p.child('Global','trigger delay').value()
            if (trigger_delay != 0):
                logger.info(f"Trigger delay ({trigger_delay} s)...")
            self.trigger_delay_timer.start(trigger_delay*1000)
            
    def start_run_button_down(self):
        #self.runTabRunsComboBox.setCurrentIndex(0) - use to set shim or pulse
        #RuntabRunsComboBox: 0=shim, 1=scan
        print(self.last_run)
        print(self.trigger_info[0])
        print(f"Trigger Info: {self.trigger_info}")
        if self.trigger_info[0] == "scan":
            self.runTabRunsComboBox.setCurrentText("Pulse Acquire")
        elif self.trigger_info[0] == "shim":
            self.last_run = self.trigger_info[0]
            self.runTabRunsComboBox.setCurrentText("Shim")
        

        self.run_isrunning = True       # must be reset by the run when it finishes
        self.trigger_timer.stop()       # stop trigger timer, will be restarted by run
        #Run Dict is the list of all NPulse aquire runs?
        run_name = self.current_run_name()
        current_text = self.runTabStartButton.text()
                        
        if current_text == 'Start':
            self.run_dict[run_name].start_run(self.trigger_info[1], self.trigger_info[2],self.trigger_info[3])
            #Variables: file_name, save_directory, shim_file
        elif current_text == 'Stop':
            self.run_dict[run_name].finish_run()
        elif current_text == 'Stopping...':
            pass
        else:
            logger.error('Start button current text not recognized')
            
    def txFreqSpinBox_changed(self,value):
        self.p.child('Global','Tx freq').setValue(value)
        
    def global_txfreq_param_changed(self):
        self.txFreqSpinBox.setValue(self.p.child('Global','Tx freq').value())
        
    def closeEvent(self, event):
        self.save_settings()
        time.sleep(0.5)
      
    
    ################
    # slots, Run tab
    def runTabRunsComboBox_index_changed(self,value):
    
        # set up UI for selected run
        run_name = self.current_run_name()
        self.run_dict[run_name].setup_UI()
        
        # clear plot data
        self.spect=[]   
        self.freqs=[]
        self.fid=[]
        self.times=[]

        # set up plots
        if self.p.child('Global','FID plot').value():
            self.runTab_setup_two_subplots()
        else:
            self.runTab_setup_one_subplot()
            
        self.set_initial_runTab_plot_limits()  # starting limits with spectrum x reversed
        self.runTabCanvas.draw()
        self.plots_blank = True   # flag to autoscale first time axes are used

    def fullX_button_down(self): 
        self.plot_spectrum(xauto=True, yauto=False)
        self.runTabCanvas.draw()

    def fullY_button_down(self): 
        self.plot_spectrum(xauto=False, yauto=True)
        self.runTabCanvas.draw()
                  
    def runTabFidCheckBox_changed(self, state):
        checked = bool(state)
        self.p.child('Global','FID plot').setValue(checked)
        # save and restore limits since runTab_setup_ will reset them
        if hasattr(self.axes,'shape'):        # if >1 subplots
            xlim_old = self.axes[1].get_xlim()
            ylim_old = self.axes[1].get_ylim()
        else:
            xlim_old = self.axes.get_xlim()
            ylim_old = self.axes.get_ylim()
        if checked:     # show FID, 1 --> 2 subplots
            self.runTab_setup_two_subplots()
            self.axes[1].set_xlim(xlim_old)
            self.axes[1].set_ylim(ylim_old)
            self.plot_fid()         # FID always autoscales
        else:                       # hide FID, 2 --> 1 subplots
            self.runTab_setup_one_subplot()
            self.axes.set_xlim(xlim_old)
            self.axes.set_ylim(ylim_old)
        self.plot_spectrum(xauto=False, yauto=False)
        if self.fid == [] or self.spect == []:
            self.set_initial_runTab_plot_limits()
        self.runTabCanvas.draw()
    
    def phasingCheckBox_changed(self, state):
        checked = bool(state)    # unchkd=0, chkd=2
        self.runTabPhaseFrame.setVisible(checked)
        self.p.child('Global','show phasing').setValue(checked)            
    
    def showphasing_param_changed(self):
        self.phasingCheckBox.setChecked(
            self.p.child('Global','show phasing').value())
    
    def fidplot_param_changed(self):
        self.runTabFidCheckBox.setChecked(
            self.p.child('Global','FID plot').value())
    
    def runTabTestCheckBox_changed(self,state):
        checked = bool(state)
        self.p.child('Global','test scan').setValue(checked)
        
    def testscan_param_changed(self):
        self.runTabTestCheckBox.setChecked( 
            self.p.child('Global','test scan').value())
    
    def hzplot_param_changed(self):
        self.runTabHzCheckBox.setChecked(
            self.p.child('Global','Hz plot').value())
        
    def runTabHzCheckBox_changed(self, state):
        plot_Hz = bool(state)    # unchkd=0, chkd=2
        self.p.child('Global','Hz plot').setValue(plot_Hz)
        run_name = self.current_run_name()
        fL = self.p.child('Global','Tx freq').value()
        offset = self.p.child(run_name,'Processing','ppm offset').value()
        two_plots = hasattr(self.axes,'shape')    # if >1 subplots
        xlim_new = [0,0]
        
        if two_plots and plot_Hz:          # ppm  --> Hz
            xlim = self.axes[1].get_xlim()
            xlim_new[0] = xlim[0]*fL + offset
            xlim_new[1] = xlim[1]*fL + offset
            self.axes[1].set_xlim(xlim_new)
            self.axes[1].set_xlabel('Frequency (Hz)',fontsize=9)
            
        if not two_plots and plot_Hz:
            xlim = self.axes.get_xlim()
            xlim_new[0] = xlim[0]*fL + offset
            xlim_new[1] = xlim[1]*fL + offset
            self.axes.set_xlim(xlim_new)
            self.axes.set_xlabel('Frequency (Hz)',fontsize=9)
            
        if two_plots and not plot_Hz:      # Hz --> ppm
            xlim = self.axes[1].get_xlim()
            xlim_new[0] = (xlim[0] - offset)/fL       
            xlim_new[1] = (xlim[1] - offset)/fL
            self.axes[1].set_xlim(xlim_new)
            self.axes[1].set_xlabel('Frequency (ppm)',fontsize=9)
            
        if not two_plots and not plot_Hz:
            xlim = self.axes.get_xlim()
            xlim_new[0] = (xlim[0] - offset)/fL       
            xlim_new[1] = (xlim[1] - offset)/fL
            self.axes.set_xlim(xlim_new)
            self.axes.set_xlabel('Frequency (ppm)',fontsize=9)
            
        self.plot_spectrum(xauto=False, yauto=False)
        self.runTabCanvas.draw()

    def phasephi0_param_changed(self):
        self.plot_spectrum(xauto=False, yauto=False)
        self.runTabCanvas.draw()
        
    def phi0_slider_pressed(self):
        self.start_phi0 = self.p.child(self.current_run_name(),'Processing','phase phi 0').value()
    def phi0_slider_moved(self):
        # phi0 range -180 --> +180 per coarse stroke
        dphi0 = 180*(self.runTabPhi0SliderC.value()+self.runTabPhi0SliderF.value()/10)\
                              /self.phi_slider_range
        phi0 = self.mod_angle(self.start_phi0+dphi0)
        self.p.child(self.current_run_name(),'Processing','phase phi 0').setValue(phi0)
        self.plot_spectrum(xauto=False, yauto=False)
        self.runTabCanvas.draw()
    def phi0_slider_released(self):
        self.runTabPhi0SliderC.setValue(0)
        self.runTabPhi0SliderF.setValue(0)
    
    def phasephi1_param_changed(self):
        self.plot_spectrum(xauto=False, yauto=False)
        self.runTabCanvas.draw()
    
    def phi1_slider_pressed(self):
        self.start_phi1 = self.p.child(self.current_run_name(),'Processing','phase phi 1').value()
    def phi1_slider_moved(self):
        # phi1 range -720/(sw) --> +720/(sw) 
        sw = self.p.child(self.current_run_name(),'Sequencer','spectral width').value()        
        dphi1 = (720/(1000*sw))* \
          (self.runTabPhi1SliderC.value()+self.runTabPhi1SliderF.value()/10)/self.phi_slider_range
        phi1 = self.start_phi1+dphi1
        self.p.child(self.current_run_name(),'Processing','phase phi 1').setValue(phi1)
        self.plot_spectrum(xauto=False, yauto=False)
        self.runTabCanvas.draw()
    def phi1_slider_released(self):
        self.runTabPhi1SliderC.setValue(0)
        self.runTabPhi1SliderF.setValue(0)
        
    def phasepivot_param_changed(self):
        self.draw_pivot_line()
        
    def pivot_slider_pressed(self):
        self.start_pivot = self.p.child(self.current_run_name(),'Processing','phase pivot').value()
    def pivot_slider_moved(self):
        # pivot range -sw/4 --> sw/4
        sw = self.p.child(self.current_run_name(),'Sequencer','spectral width').value()
        dpivot = -(1000*sw/4)*(self.runTabPivotSliderC.value()+self.runTabPivotSliderF.value()/40)\
                           /self.pivot_slider_range
        pivot = self.start_pivot+dpivot
        self.p.child(self.current_run_name(),'Processing','phase pivot').setValue(pivot)
        self.draw_pivot_line()
    def pivot_slider_released(self):
        self.runTabPivotSliderC.setValue(0)
        self.runTabPivotSliderF.setValue(0)
   
    def ppmoffset_param_changed(self):
        self.plot_spectrum(xauto=False, yauto=False)
        self.runTabCanvas.draw()
   
    def ppmoffset_slider_pressed(self):
        self.start_offset = self.p.child(self.current_run_name(),'Processing','ppm offset').value()
    def ppmoffset_slider_moved(self):
        # offset range -sw/4 --> sw/4
        sw = self.p.child(self.current_run_name(),'Sequencer','spectral width').value()
        doffset = -(1000*sw/4)*(self.runTab0ppmSliderC.value()+self.runTab0ppmSliderF.value()/40)\
                           /self.offset_slider_range
        offset = self.start_offset+doffset
        self.p.child(self.current_run_name(),'Processing','ppm offset').setValue(offset)
        self.plot_spectrum(xauto=False, yauto=False)
        self.runTabCanvas.draw()
    def ppmoffset_slider_released(self):
        self.runTab0ppmSliderC.setValue(0)
        self.runTab0ppmSliderF.setValue(0)

        
    ###################
    # slots, Magnet tab
    def mag_plot(self):
        maxpts = 1200      # 1200 samples = 4 hours
        stats_samples = 25 # number of samples for stats, 25 = 5 min
        
        if not self.si.configured: # no hardware present
            return
        
        if self.run_isrunning:     # block RS485 comms to temp controller when a run is running
            return
        
        T_point, enc_point,_,_ = tc.get_MAP(self.si)  # get aliased temperature
        power_point,_,_ = tc.get_PWR(self.si)
        
        if len(self.mag_T) < maxpts:
            self.mag_T.append(T_point)
        else:
            self.mag_T.pop(0)
            self.mag_T.append(T_point)
            
        if len(self.mag_enclosure) < maxpts:
            self.mag_enclosure.append(enc_point)
        else:
            self.mag_enclosure.pop(0)
            self.mag_enclosure.append(enc_point)
            
        if len(self.mag_power) < maxpts:
            self.mag_power.append(power_point)
        else:
            self.mag_power.pop(0)
            self.mag_power.append(power_point)
            
        mag_time = time.perf_counter()/60
        if len(self.mag_times) < maxpts:
            self.mag_times.append(mag_time)
        else:
            self.mag_times.pop(0)
            self.mag_times.append(mag_time)       
        #print('read magnet :', T_point ,enc_point ,power_point ,mag_time)
            
        self.mag_times_0 = [t - self.mag_times[0] for t in self.mag_times]
        self.magAxes[0].clear()
        self.magAxes[1].clear()
        self.magAxes[2].clear()
        self.magAxes[0].plot(self.mag_times_0, self.mag_T, linewidth=1)
        self.magAxes[1].plot(self.mag_times_0, self.mag_enclosure, linewidth=1)
        self.magAxes[2].plot(self.mag_times_0, self.mag_power, linewidth=1)
        
        # report statistics, will throw error if there are any None points in mag_T
        # will happen if temperature controller board does not respond
        try:
            if len(self.mag_T) > stats_samples:
                aveT = statistics.mean(self.mag_T[-(stats_samples+1):-1])
                sigmaT = statistics.stdev(self.mag_T[-(stats_samples+1):-1])
                msg = f'mean = {aveT:2.6f} C, std. dev. = {sigmaT*1000:0.3f} mC (5 min)'
                self.magAxes[0].text(0.03, 0.80, msg, transform=self.magAxes[0].transAxes, fontsize = 7)
        except:
            logger.error(f"Error computing temperature statistics")

        self.magAxes[0].tick_params(direction ='in', right='True', top='True',labelsize=9)
        self.magAxes[1].tick_params(direction ='in', right='True', top='True',labelsize=9)
        self.magAxes[2].tick_params(direction ='in', right='True', top='True',labelsize=9)
        self.magAxes[0].set_ylabel('magnet (C)')
        self.magAxes[0].yaxis.set_major_formatter(FormatStrFormatter('% 2.6f'))
        self.magAxes[1].set_ylabel('ambient (C)')
        self.magAxes[1].yaxis.set_major_formatter(FormatStrFormatter('% 2.6f'))
        self.magAxes[2].set_xlabel('time (minutes)')
        self.magAxes[2].set_ylabel('heater (W)')
        self.magAxes[2].yaxis.set_major_formatter(FormatStrFormatter('% 2.6f'))
        
        #logger.info('Temperature plot updated')
        self.magTabCanvas.draw()
        
    def mag_setParam_button_down(self):
        if not self.si.configured:   # no hardware present
            logger.error(f"No spectrometer present on USB")
            return
        set_point_T = self.p.child('Global','Magnet','set point T').value()
        control_P =  self.p.child('Global','Magnet','control P').value()
        control_I =  self.p.child('Global','Magnet','control I').value()
        control_D =  self.p.child('Global','Magnet','control D').value()

        logger.info('Set temperature controller parameters... ')
        logger.info(f'T = {set_point_T:0.4f}, P = {control_P:0.1E}, I = {control_I:0.1E}, D = {control_D:0.1E}')
        tc.set_TMS(self.si, set_point_T)                           # temperature control set point
        tc.set_PID(self.si, control_P, control_I, control_D)       # PID parameters
        tc.set_HEN(self.si,1)                                      # heater enable
        tc.SAV(self.si)                                            # save temperature control parameters to flash

        
    def magTabPausePlotCheckBox_state_changed(self,state):
        if state == Qt.Checked:
            self.mag_timer.stop()
        else:
            self.mag_timer.start(self.mag_sample_delay*1000)
    
    def magTabSetTSpinBox_changed(self,value):
        self.p.child('Global','Magnet','set point T').setValue(value)
    
    def mag_setT_param_changed(self):
        self.magTabSetTSpinBox.setValue(self.p.child('Global','Magnet','set point T').value())
 
 
    ##################   
    # helper functions    
    def heartbeat(self): 
        self. logger.info(str(self.inter))     
        self.inter += 1
    
    # string for a parameterTree path
    def current_run_name(self):
        return self.runTabRunsComboBox.currentText() + " Run"
    
    # return any angle to range -180 to +180
    def mod_angle(self,angle):
        return ((angle + 180) % 360) - 180
    
    # reasonable limits when there is no plot data yet
    def set_initial_runTab_plot_limits(self):
        fL = self.p.child('Global','Tx freq').value()
        sw = self.p.child(self.current_run_name(),'Sequencer','spectral width').value()  
        fid_ylim = [-100,100]
        fid_xlim = [-0.1,2.1]
        spect_ylim = [-50,1000]
        if self.p.child('Global','Hz plot').value():
            spect_xlim = [1100*sw/2,-1100*sw/2]   # reversed
        else:
            spect_xlim = [1100*sw/(2*fL),-1100*sw/(2*fL)]  
        if hasattr(self.axes,'shape'):          # if >1 subplots
            self.axes[0].set_xlim(fid_xlim)
            self.axes[0].set_ylim(fid_ylim)
            self.axes[1].set_xlim(spect_xlim)
            self.axes[1].set_ylim(spect_ylim)
        else:
            self.axes.set_xlim(spect_xlim)
            self.axes.set_ylim(spect_ylim)
    
    def draw_pivot_line(self):
        fL, phi0, phi1, pivot, offset, plot_Hz, plot_mag = self.get_plotting_params(self.current_run_name())
        self.plot_spectrum(xauto=False, yauto=False)     
        if plot_Hz:
            pivot_line = pivot
        else:
            pivot_line = (pivot - offset)/fL  
        if hasattr(self.axes,'shape'):    # if >1 subplots
            self.axes[1].lines[1].set_data([pivot_line, pivot_line], [-10**10,10**10]) 
        else:
            self.axes.lines[1].set_data([pivot_line, pivot_line], [-10**10,10**10])
        self.runTabCanvas.draw()
    
    # run tab, for plotting spectrum only
    def runTab_setup_one_subplot(self): 
        self.runTabCanvas.figure.clear()        
        self.axes = self.runTabCanvas.figure.subplots(1,1)
        self.runTabCanvas.figure.subplots_adjust(
            top=0.96,
            bottom=0.15,
            left=0.091,
            right=0.956)
        self.axes.tick_params(direction ='in', right='True', top='True',labelsize=9)
        if self.p.child('Global','Hz plot').value():
            self.axes.set_xlabel('Frequency (Hz)',fontsize=9)
        else:
            self.axes.set_xlabel('Frequency (ppm)',fontsize=9)
        self.axes.plot([], [], [], [], linewidth=1)  # 2nd curve is for pivot line
    
    # run tab, for plotting spectrum and fid
    def runTab_setup_two_subplots(self):
        self.runTabCanvas.figure.clear()        
        self.axes = self.runTabCanvas.figure.subplots(2,1)
        self.runTabCanvas.figure.subplots_adjust(
             top=0.96,
             bottom=0.15,
             left=0.091,
             right=0.956,
             hspace=0.391,
             wspace=0.165)
        self.axes[0].tick_params(direction ='in', right='True', top='True',labelsize=9)        
        self.axes[0].set_xlabel('Time (s)',fontsize=9)
        self.axes[0].plot([], [], linewidth=1) 
        self.axes[1].tick_params(direction ='in', right='True', top='True',labelsize=9)
        if self.p.child('Global','Hz plot').value():
            self.axes[1].set_xlabel('Frequency (Hz)',fontsize=9)
        else:
            self.axes[1].set_xlabel('Frequency (ppm)',fontsize=9)
        self.axes[1].plot([], [], [], [], linewidth=1)  # 2nd curve is for pivot line
    
    # set up axes for magnet tab plots
    def mag_setup_plots(self):
        self.magTabCanvas.figure.clear()        
        self.magAxes = self.magTabCanvas.figure.subplots(3,1, sharex=True)
        self.magTabCanvas.figure.subplots_adjust(
            top=0.93,
            bottom=0.139,
            left=0.179,
            right=0.93,
            hspace=0.2,
            wspace=0.23)
    
    # parameters needed in run tab plotting functions    
    def get_plotting_params(self, run_name):
        #Start with some default values so that the program doesn't hang if they're not present
        #Probably need to change control flow so that the program gracefully handles missing parameters
        fL = 124.2
        phi0 = 0
        phi1 = 0
        pivot = 0
        offset = 0
        plot_mag = True
        plot_Hz = True
        try:
            fL = self.p.child('Global','Tx freq').value()
            phi0 = self.p.child(run_name,'Processing','phase phi 0').value()
            phi1 = self.p.child(run_name,'Processing','phase phi 1').value()
            pivot = self.p.child(run_name,'Processing','phase pivot').value()
            offset = self.p.child(run_name,'Processing','ppm offset').value()
            plot_mag = self.p.child(run_name,'Processing','plot mag').value()
            plot_Hz = self.p.child('Global','Hz plot').value()
            plot_real = True            # not implemented so always treat as if True
        except Exception as e:
            logger.exception("Problem retrieving plotting parameters")
            #TODO: just threw a self. here so that the box doesn't disapper immediatly, need to refactor
            self.msgBox = QMessageBox()
            self.msgBox.setIcon(QMessageBox.Critical)
            self.msgBox.setWindowTitle("Parameter issue")
            self.msgBox.setText("There was a problem retrieving plotting parameters")
            self.msgBox.setInformativeText(str(e))
            self.msgBox.setStandardButtons(QMessageBox.Ok)
            self.msgBox.show()
        return fL, phi0, phi1, pivot, offset, plot_Hz, plot_mag
 
    # return a dict of all parameters on one branch of the parameterTree  
    # path is a list of one or more strings
    # for example param_dict(['Pulse Acquire Run','Sequencer'])
    def param_dict(self, path):
        p1 = self.p.child(*path)
        return {child.name():child.value() for child in p1.children()}

    # run tab fid plot, always autoscale
    def plot_fid(self):
        marginx = 0.05
        marginy = 0.1
        # only if >1 subplots and fid has data
        if hasattr(self.axes,'shape') and len(self.fid)>0:    
             line, = self.axes[0].lines
             rfid = np.real(self.fid)
             line.set_data(self.times, rfid)                  # set data
             min = self.times.min(); max = self.times.max()   # set limits
             dx = marginx*(max - min)
             self.axes[0].set_xlim([min - dx, max + dx])
             min = rfid.min(); max = rfid.max()
             dy = marginy*(max - min)
             self.axes[0].set_ylim([min - dy, max + dy])

    # run tab spectrum plot
    # responds to plotHz/ppm, plot real/mag, autoscale settings
    # always clear the pivot line
    def plot_spectrum(self, xauto=True, yauto=True):
        marginx = 0.05
        marginy = 0.1
        if len(self.spect) > 0:                   # only if spectrum has data
            run_name = self.current_run_name()     
            fL, phi0, phi1, pivot, offset, plot_Hz, plot_mag = self.get_plotting_params(run_name)
            if plot_mag:
                pspect = np.absolute(self.spect)  # plot mag(spectrum)
            else:
                pspect = np.real(self.spect*np.exp(-1j*2*np.pi*phi0/360)\
                     *np.exp(-1j*2*np.pi*(self.freqs - pivot)*phi1/360)) 
            if not(plot_Hz):
                pfreqs = (self.freqs-offset)/fL   # convert freqs to ppm with offset
            else:
                pfreqs = self.freqs
            if hasattr(self.axes,'shape'):        # if >1 subplots need to use axes[1]
                spect_axes = self.axes[1]
            else: 
                spect_axes = self.axes

            line, pivot_line = spect_axes.lines   # get lines
            line.set_data(pfreqs, pspect)         # set plot data
            pivot_line.set_data([],[])            # clear pivot line
            
            # set limits, x is reversed per NMR convention
            if xauto:
                min = pfreqs.min(); max = pfreqs.max()
                dx = marginx*(max - min) 
                spect_axes.set_xlim([max + dx, min - dx])  # [left limit, right limit]
            if yauto:
                min = pspect.min(); max = pspect.max()
                dy = marginy*(max - min)
                spect_axes.set_ylim([min - dy, max + dy])                  
   
    global_default_settings = \
        {'name': 'Global', 'type': 'group', 'expanded': False, 'children': 
            [
            {'name': 'settingsVersion', 'type':'int', 'value': 1, 'readonly': True, "visible": False},
            {'name': 'Tx freq', 'type': 'float', 'value': 123.1892, 'step': 0.00001, 'decimals': 6, 'siSuffix': True, 'suffix': 'MHz'},
            {'name': 'shim file', 'type': 'str', 'value': 'shim_file'},
            {'name': 'test scan', 'type': 'bool', 'value': False},
            {'name': 'trigger enable', 'type': 'bool', 'value': True},
            {'name': 'trigger delay', 'type': 'float', 'value': 5.0, 'decimals': 2, 'step': 0.1, 'limits': [0,1000], 'siSuffix': True, 'suffix': 's'},
            {'name': 'show phasing', 'type': 'bool', 'value': False},
            {'name': 'FID plot', 'type': 'bool', 'value': True},
            {'name': 'Hz plot', 'type': 'bool', 'value': True},
            {'name': 'gain target', 'type': 'float', 'value': 40.0, 'step': 1, 'decimals': 2},
            {'name': 'Magnet', 'type': 'group', 'expanded': False, 'children':
                [
                {'name': 'set point T', 'type': 'float', 'value': 32.000, 'step': 0.001, 'decimals': 5, 'siSuffix': True, 'suffix': 'C', 'limits': [20,45]},
                {'name': 'control P', 'type': 'float', 'value': 8E9, 'step': 1E8, 'decimals': 2},
                {'name': 'control I', 'type': 'float', 'value': 6E8, 'step': 1E8, 'decimals': 2},
                {'name': 'control D', 'type': 'float', 'value': 2E10, 'step': 1E8, 'decimals': 2}
                ]},
            {'name': 'Service', 'type': 'group', 'expanded': False, 'children':
                [
                {'name': 'verbose', 'type': 'bool', 'value': False},
                {'name': 'simulate', 'type': 'bool', 'value': False}
                ]
                }
            ]
        }

# if __name__ == "__main__":

    # os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1" 
    # app = QApplication(sys.argv)
    # app.setStyle('Fusion') 
    # mainwindow = MainWindow()
    # mainwindow.show()
    # sys.exit(app.exec_())
