# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_component_dialog_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QFrame, QWidget
from valve_port_setter import ValvePortSetter

class AddComponentDialog( QDialog  ):
    def __init__(self, parent):

        super().__init__()
        self.setupUi(self)


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.hbox = QtWidgets.QHBoxLayout()
        self.right_vbox = QtWidgets.QVBoxLayout()
        self.left_vbox =QtWidgets.QVBoxLayout()
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 240, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.right_vbox.addWidget(self.buttonBox)
        self.ComponentName = QtWidgets.QLineEdit(Dialog)
        self.ComponentName.setGeometry(QtCore.QRect(10, 20, 181, 20))
        self.ComponentName.setObjectName("ComponentName")
        self.ComponentName.setPlaceholderText("Enter Component Name")
        self.left_vbox.addWidget(self.ComponentName)

        #self.Valves = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        #self.Valves.setContentsMargins(0, 0, 0, 0)
        #self.Valves.setObjectName("Valves")
        #self.Valves.setSpacing(5)
 

        self.AddConnection = QtWidgets.QPushButton(Dialog)
        self.AddConnection.setGeometry(QtCore.QRect(10, 230, 121, 23))
        self.AddConnection.setObjectName("AddConnection")
        self.left_vbox.addWidget(self.AddConnection)
        self.AddConnection.clicked.connect(self.add_component)
        self.RemoveConnection = QtWidgets.QPushButton(Dialog)
        self.RemoveConnection.setGeometry(QtCore.QRect(10, 250, 121, 23))
        self.RemoveConnection.setObjectName("RemoveConnection")
        self.left_vbox.addWidget(self.RemoveConnection)
        self.HotplateSelector = QtWidgets.QComboBox(Dialog)
        self.HotplateSelector.setGeometry(QtCore.QRect(220, 20, 151, 22))
        self.HotplateSelector.setObjectName("HotplateSelector")
        self.left_vbox.addWidget(self.HotplateSelector)
        self.HotplateSelector.addItem("")
        self.HotplateSelector.addItem("")
        self.HotplateSelector.addItem("")
        self.HotplateSelector.addItem("")
        self.IsUsed = QtWidgets.QCheckBox(Dialog)
        self.IsUsed.setGeometry(QtCore.QRect(220, 70, 121, 17))
        self.IsUsed.setObjectName("IsUsed")
        self.left_vbox.addWidget(self.IsUsed)
        self.hbox.addLayout(self.left_vbox)
        self.hbox.addLayout(self.right_vbox)
        self.retranslateUi(Dialog)
        self.setLayout(self.hbox)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AddConnection.setText(_translate("Dialog", "Add Connection"))
        self.RemoveConnection.setText(_translate("Dialog", "Remove Connection"))
        self.HotplateSelector.setItemText(0, _translate("Dialog", "hotplate_1"))
        self.HotplateSelector.setItemText(1, _translate("Dialog", "hotplate_2"))
        self.HotplateSelector.setItemText(2, _translate("Dialog", "hotplate_3"))
        self.HotplateSelector.setItemText(3, _translate("Dialog", "hotplate_4"))
        self.IsUsed.setText(_translate("Dialog", "Already Filled?"))

    def add_component(self):
        new_comp = ValvePortSetter()
        self.right_vbox.addWidget(new_comp)
        #self.Valves.addStretch()
    def remove_component(self):
        pass

    def get_connections(self):
        specific_widgets = [ w.get_values() for w in self.right_vbox.children() if isinstance(w, ValvePortSetter)]
        return specific_widgets
#        self.setLayout(self.Valves)
    def _update_json_entry(self):
        self.component = {self.ComponentName.text(): {
        "type": "vial",
        "hotplate":self.HotplateSelector.currentText(),
        "used":self.IsUsed.isChecked(),
        "volume":100,
        "valve_connections":self.get_connections(),
        "cleaning":[]
            }
        }
        print("Updated")