# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dryan.local\Desktop\MM_exact_polymer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
from ExactPolymerReactionClass import ExactPolymerReactionPlan
from add_component_dialog_box import AddComponentDialog
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.reaction_plan = ExactPolymerReactionPlan()
        self.components = {}
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1117, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label.setObjectName("label")
        self.PolymerLength = QtWidgets.QSpinBox(self.centralwidget)
        self.PolymerLength.setGeometry(QtCore.QRect(10, 30, 42, 22))
        self.PolymerLength.setMinimum(1)
        self.PolymerLength.setMaximum(16)
        self.PolymerLength.setObjectName("PolymerLength")
        self.solid_supported_polymer = QtWidgets.QCheckBox(self.centralwidget)
        self.solid_supported_polymer.setGeometry(QtCore.QRect(10, 60, 271, 20))
        self.solid_supported_polymer.setObjectName("solid_supported_polymer")
        self.orthogonally_protected_monomer = QtWidgets.QCheckBox(self.centralwidget)
        self.orthogonally_protected_monomer.setGeometry(QtCore.QRect(10, 80, 271, 20))
        self.orthogonally_protected_monomer.setObjectName("orthogonally_protected_monomer")
        self.monomer_removal_solid_supported = QtWidgets.QCheckBox(self.centralwidget)
        self.monomer_removal_solid_supported.setGeometry(QtCore.QRect(10, 100, 271, 20))
        self.monomer_removal_solid_supported.setObjectName("monomer_removal_solid_supported")
        self.activator_solid_supported = QtWidgets.QCheckBox(self.centralwidget)
        self.activator_solid_supported.setGeometry(QtCore.QRect(10, 120, 271, 20))
        self.activator_solid_supported.setObjectName("activator_solid_supported")
        self.end_cap = QtWidgets.QCheckBox(self.centralwidget)
        self.end_cap.setGeometry(QtCore.QRect(10, 140, 271, 20))
        self.end_cap.setObjectName("end_cap")
        self.Monomer = QtWidgets.QComboBox(self.centralwidget)
        self.Monomer.setGeometry(QtCore.QRect(440, 10, 341, 22))
        self.Monomer.setMinimumSize(QtCore.QSize(341, 0))
        self.Monomer.setObjectName("Monomer")
        self.Monomer.addItem("")
        self.Monomer.currentTextChanged.connect(lambda: self.set_atr( "MonomerSolution", self.Monomer.currentText()))
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 161, 16))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.CouplingReactionComponent = QtWidgets.QComboBox(self.centralwidget)
        self.CouplingReactionComponent.setGeometry(QtCore.QRect(440, 40, 341, 22))
        self.CouplingReactionComponent.setMinimumSize(QtCore.QSize(341, 0))
        self.CouplingReactionComponent.setObjectName("CouplingReactionComponent")
        self.CouplingReactionComponent.currentTextChanged.connect(lambda: self.set_atr( "CouplingReactionComponent", self.CouplingReactionComponent.currentText()))
        self.CouplingReactionComponent.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 40, 271, 20))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 100, 391, 20))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.ExcessMonomerWash = QtWidgets.QComboBox(self.centralwidget)
        self.ExcessMonomerWash.setGeometry(QtCore.QRect(440, 70, 341, 22))
        self.ExcessMonomerWash.setMinimumSize(QtCore.QSize(341, 0))
        self.ExcessMonomerWash.setObjectName("ExcessMonomerWash")
        self.ExcessMonomerWash.addItem("")
        self.ExcessMonomerWash.currentTextChanged.connect(lambda: self.set_atr( "ExcessMonomerWash", self.ExcessMonomerWash.currentText()))
        self.ActivatorComponent = QtWidgets.QComboBox(self.centralwidget)
        self.ActivatorComponent.setGeometry(QtCore.QRect(440, 100, 341, 22))
        self.ActivatorComponent.setMinimumSize(QtCore.QSize(341, 0))
        self.ActivatorComponent.setObjectName("ActivatorComponent")
        self.ActivatorComponent.addItem("")
        self.ActivatorComponent.currentTextChanged.connect(lambda: self.set_atr( "ActivatorComponent", self.ActivatorComponent.currentText()))
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 411, 20))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 431, 20))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.ExcessActivatorWash = QtWidgets.QComboBox(self.centralwidget)
        self.ExcessActivatorWash.setGeometry(QtCore.QRect(440, 130, 341, 22))
        self.ExcessActivatorWash.setMinimumSize(QtCore.QSize(341, 0))
        self.ExcessActivatorWash.setObjectName("ExcessActivatorWash")
        self.ExcessActivatorWash.addItem("")
        self.ExcessActivatorWash.currentTextChanged.connect(lambda: self.set_atr( "ExcessActivatorWash", self.ExcessActivatorWash.currentText()))
        self.CleavingComponent = QtWidgets.QComboBox(self.centralwidget)
        self.CleavingComponent.setGeometry(QtCore.QRect(440, 160, 341, 22))
        self.CleavingComponent.setMinimumSize(QtCore.QSize(341, 0))
        self.CleavingComponent.setObjectName("CleavingComponent")
        self.CleavingComponent.addItem("")
        self.CleavingComponent.currentTextChanged.connect(lambda: self.set_atr( "CleavingComponent", self.CleavingComponent.currentText()))
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 431, 20))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 431, 20))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.EndCap = QtWidgets.QComboBox(self.centralwidget)
        self.EndCap.setGeometry(QtCore.QRect(440, 190, 341, 22))
        self.EndCap.setMinimumSize(QtCore.QSize(341, 0))
        self.EndCap.setObjectName("EndCap")
        self.EndCap.addItem("")
        self.EndCap.currentTextChanged.connect(lambda: self.set_atr( "EndCapComponent", self.EndCap.currentText()))
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 220, 271, 20))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.ActivatorVial = QtWidgets.QComboBox(self.centralwidget)
        self.ActivatorVial.setGeometry(QtCore.QRect(440, 250, 341, 22))
        self.ActivatorVial.setMinimumSize(QtCore.QSize(341, 0))
        self.ActivatorVial.setObjectName("ActivatorVial")
        self.ActivatorVial.addItem("")
        self.ActivatorVial.currentTextChanged.connect(lambda: self.set_atr( "ActivatorVial", self.ActivatorVial.currentText()))
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 250, 411, 20))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.MonomerAbsorber = QtWidgets.QComboBox(self.centralwidget)
        self.MonomerAbsorber.setGeometry(QtCore.QRect(440, 220, 341, 22))
        self.MonomerAbsorber.setMinimumSize(QtCore.QSize(341, 0))
        self.MonomerAbsorber.setObjectName("MonomerAbsorber")
        self.MonomerAbsorber.addItem("")
        self.AddComponentDialogButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddComponentDialogButton.setGeometry(QtCore.QRect(440, 420, 341, 22))
        self.AddComponentDialogButton.setMinimumSize(QtCore.QSize(341, 0))
        self.AddComponentDialogButton.setObjectName("AddComponentDialogButton")
        self.AddComponentDialogButton.clicked.connect(lambda: self.add_component())
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 320, 191, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self._on_start_press)
        self.ReloadComponentsButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReloadComponentsButton.setGeometry(QtCore.QRect(20, 230, 191, 71))
        self.ReloadComponentsButton.setObjectName("ReloadComponentsButton")
        self.ReloadComponentsButton.clicked.connect(self.load_components)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.set_connections(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def set_connections(self, MainWindow):
        for checkbox in self.centralwidget.findChildren(QtWidgets.QCheckBox):
            checkbox.toggled.connect(lambda: self._set_block_attributes(MainWindow))


    def _set_block_attributes(self,MainWindow):
        
        # End Cap Component 
        self.EndCap.setEnabled( self.end_cap.isChecked())

        #Monomer Absorber vial if solid supported
        self.MonomerAbsorber.setEnabled( self.monomer_removal_solid_supported.isChecked())
        
        #solid supported polymer
        self.CleavingComponent.setEnabled( self.solid_supported_polymer.isChecked())
        
        #Activator Vial solid supported
        self.ActivatorVial.setEnabled( self.activator_solid_supported.isChecked())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose Reaction Length"))
        self.solid_supported_polymer.setText(_translate("MainWindow", "solid_supported_polymer"))
        self.orthogonally_protected_monomer.setText(_translate("MainWindow", "orthogonally_protected_monomer"))
        self.monomer_removal_solid_supported.setText(_translate("MainWindow", "monomer_removal_solid_supported"))
        self.activator_solid_supported.setText(_translate("MainWindow", "activator_solid_supported"))
        self.end_cap.setText(_translate("MainWindow", "end_cap"))
        self.Monomer.setItemText(0, _translate("MainWindow", "None"))
        self.label_2.setText(_translate("MainWindow", "Monomer Solution:"))
        self.CouplingReactionComponent.setItemText(0, _translate("MainWindow", "None"))
        self.label_3.setText(_translate("MainWindow", "Coupling Reaction Component:"))
        self.label_4.setText(_translate("MainWindow", "Activator Component:"))
        self.ExcessMonomerWash.setItemText(0, _translate("MainWindow", "None"))
        self.ActivatorComponent.setItemText(0, _translate("MainWindow", "None"))
        self.label_5.setText(_translate("MainWindow", "Excess Monomer Wash:"))
        self.label_6.setText(_translate("MainWindow", "Cleaving Component:"))
        self.ExcessActivatorWash.setItemText(0, _translate("MainWindow", "None"))
        self.CleavingComponent.setItemText(0, _translate("MainWindow", "None"))
        self.label_7.setText(_translate("MainWindow", "Excess Activator Wash:"))
        self.label_8.setText(_translate("MainWindow", "End Cap Component:"))
        self.EndCap.setItemText(0, _translate("MainWindow", "None"))
        self.label_9.setText(_translate("MainWindow", "Monomer Absorber Vial:"))
        self.ActivatorVial.setItemText(0, _translate("MainWindow", "None"))
        self.label_12.setText(_translate("MainWindow", "Activator Vial:"))
        self.MonomerAbsorber.setItemText(0, _translate("MainWindow", "None"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.ReloadComponentsButton.setText(_translate("MainWindow", "Reload Component"))
        self.AddComponentDialogButton.setText(_translate("MainWindow", "Add Component"))

    def load_components(self):
        
        with open('.\CampaignSetup\components.json') as file:
            self.components = self.components | json.load(file)
            selectors = self.centralwidget.findChildren(QtWidgets.QComboBox)
            
            for component in self.components:
                for selector in selectors:
                    selector.addItem(component)
        with open('.\CampaignSetup\components.json', 'w') as file:
            json.dump(self.components, file)
    def update_components(self):
        selectors = self.centralwidget.findChildren(QtWidgets.QComboBox)
            
        for component in self.components:
            for selector in selectors:
                selector.addItem(component)
    def add_component(self):
            # Pass 'self' as parent to center the dialog over the main window
        dlg = AddComponentDialog(self)
        if dlg.exec():
            dlg._update_json_entry()
            self.components = self.components | dlg.component
            self.update_components()
            print(self.components)
        else:
            print("Dialog was canceled.")

    def set_atr(self, start_value, new_value):
        self.reaction_plan.__setattr__(start_value,new_value)

    def _on_start_press(self):
        pass

    ##TODO Add component window
    ##TODO 2 Grey out non-relevant components
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
