# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'valve_port_setter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.QtWidgets import QApplication, QWidget, QSpinBox, QVBoxLayout, QLabel, QHBoxLayout
class ValvePortSetter(QWidget):
    def __init__(self):
        super().__init__()
        self.init_ui()

    def init_ui(self):
        # 1. Initialize a vertical layout manager
        layout = QHBoxLayout()
        layout.setSpacing(3)

        # 2. Configure the first spin box
        self.label1 = QLabel("Valve:")
        self.spin_box1 = QSpinBox()
        self.spin_box1.setRange(1, 24)
        self.spin_box1.setValue(1)

        # 3. Configure the second spin box
        self.label2 = QLabel("Port:")
        self.spin_box2 = QSpinBox()
        self.spin_box2.setRange(1, 8)
        self.spin_box2.setValue(1)
    

        # 4. Pack items sequentially into layout
        layout.addWidget(self.label1)
        layout.addWidget(self.spin_box1)
        layout.addWidget(self.label2)
        layout.addWidget(self.spin_box2)

        # 5. Commit layout to the parent window
        self.setLayout(layout)
        self.setWindowTitle("Qt Dual SpinBox Example")
        self.resize(50, 50)
        self.setMaximumSize(250,50)

    # Helper methods to grab current integer values
    def get_values(self):
        return [self.spin_box1.value(), self.spin_box2.value()]